const restaurant_data = [
  {
    id: "100",
    name: "McDonalds",
    type: "Take-Away",
    tags: [
      "burgers",
      "chicken",
      "coffee",
      "tea",
      "drinks",
      "pizza",
      "desserts",
      "chocolate",
      "sundae",
      "paneer",
      "nuggets",
    ],
    location: "13A Street, New York",
    distance: 5000,
    time: 30,
    images: {
      logo: require("../assets/logo/mcdonalds.png"),
      poster: require("../assets/poster/sd/mcdonalds.png"),
      cover: require("../assets/gallery/square/sd/burgers.png"),
    },
    categories: ["Burgers & Wraps", "Snacks & Sides", "Desserts", "Beverages"],
  },
  {
    id: "101",
    name: "Burger King",
    type: "Dine-In",
    tags: ["burgers", "chicken", "veg", "grilled", "fries"],
    location: "15th Avenue, New York",
    distance: 3900,
    time: 25,
    images: {
      logo: require("../assets/logo/burgerking.png"),
      poster: require("../assets/poster/sd/burgerking.png"),
      cover: require("../assets/gallery/square/sd/burgerking.png"),
    },
    categories: ["Burgers", "Whopper", "Chicken Wings", "Sides"],
  },
  {
    id: "102",
    name: "Dominos Pizza",
    type: "Dine-In",
    tags: [
      "pizza",
      "chicken",
      "barbeque",
      "sausage",
      "indian",
      "veg",
      "mexican",
      "paneer",
      "bread",
    ],
    location: "15th Avenue, New York",
    distance: 6300,
    time: 35,
    images: {
      logo: require("../assets/logo/dominos.png"),
      poster: require("../assets/poster/sd/dominos.png"),
      cover: require("../assets/gallery/square/sd/dominospizza.png"),
    },
    categories: [
      "Non-Veg Pizza",
      "Veg Pizza",
      "Pizza Mania",
      "Sides and Beverages",
    ],
  },
  {
    id: "103",
    name: "Pizza Hut",
    type: "Dine-In",
    tags: ["Pizza", "American Foods", "Chicken", "Meat"],
    location: "15th Avenue, New York",
    distance: 5560,
    time: 31,
    images: {
      logo: require("../assets/logo/pizzahut.png"),
      poster: require("../assets/poster/sd/pizzahut.png"),
      cover: require("../assets/gallery/square/sd/pizzahut.png"),
    },
    categories: ["Pizzas", "Sides", "Desserts", "Drinks"],
  },
  {
    id: "104",
    name: "Baskin Robins",
    type: "Take-Away",
    tags: ["Icecream", "American Foods", "Desserts"],
    location: "15th Avenue, New York",
    distance: 3400,
    time: 21,
    images: {
      logo: require("../assets/logo/baskinrobbins.png"),
      poster: require("../assets/poster/sd/baskinrobbins.png"),
      cover: require("../assets/gallery/square/sd/baskinrobbins.png"),
    },
    categories: [
      "Twin Combo Packs",
      "Scoops",
      "Icecream Cakes",
      "Sundaes",
      "Icecream Sandwich",
      "Super-Duper Thick Shakes",
    ],
  },
  {
    id: "105",
    name: "Starbucks",
    type: "Cafe",
    tags: ["Coffee", "American Foods", "Tea"],
    location: "15th Avenue, New York",
    distance: 6600,
    time: 36,
    images: {
      logo: require("../assets/logo/starbucks.png"),
      poster: require("../assets/poster/sd/starbucks.png"),
      cover: require("../assets/gallery/square/sd/starbucks.png"),
    },
    categories: [
      "Featured Drinks",
      "Freshly Brewed Coffee",
      "Crème Frappuccino®",
      "Cold Brew",
      "Espresso",
      "Coffee Frappuccino®",
      "Teavana® Tea",
    ],
  },
  {
    id: "106",
    name: "Subway",
    type: "Take-Away",
    tags: ["American Foods", "Burger", "Sandwich"],
    location: "15th Avenue, New York",
    distance: 4800,
    time: 26,
    images: {
      logo: require("../assets/logo/subway.png"),
      poster: require("../assets/poster/sd/subway.png"),
      cover: require("../assets/gallery/square/sd/subway.png"),
    },
    categories: [
      "Signature Wraps",
      "All Sandwiches",
      "Breakfast",
      "Salads",
      "Snacks",
      "Sides & Drinks",
    ],
  },
  {
    id: "107",
    name: "KFC",
    type: "Dine-In",
    tags: ["American Foods", "Chicken"],
    location: "15th Avenue, New York",
    distance: 2600,
    time: 16,
    images: {
      logo: require("../assets/logo/kfc.png"),
      poster: require("../assets/poster/sd/kfc.png"),
      cover: require("../assets/poster/sd/kfc.png"),
    },
    categories: ["Chicken", "Burgers", "Rice Bowls", "Snacks", "Beverages"],
  },
];

export default restaurant_data;
